name: CD DEV

on:
  workflow_run:
    workflows: ["CI"]
    branches: [next]
    types: [completed]

permissions:
  contents: read
  packages: write

jobs:
  primary:
    name: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/_cd-dev.yaml
    with:
      runner: ubuntu-latest
    secrets: inherit

  fallback:
    name: self-hosted fallback
    needs: [primary]
    if: ${{ always() && needs.primary.result == 'failure' }}
    uses: ./.github/workflows/_cd-dev.yaml
    with:
      runner: self-hosted
    secrets: inherit
